name: daai25-mlintro
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - matplotlib
  - openpyxl=3.1.4
  - pandas
  - pip
  - python=3.10
  - seaborn
  - scikit-learn
  - tensorflow
  - pip:
      - scikit-surprise==1.1.4